---
analyzer_rules:
  - explicit_self
disabled_rules:
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - opening_brace
function_body_length:
  error: 200
  warning: 80
identifier_name:
  allowed_symbols: _
  excluded:
    - id
    - ok
  max_length:
    error: 1000
    warning: 90
  min_length: 2
nesting:
  function_level:
    error: 8
    warning: 4
  type_level:
    error: 6
    warning: 4
opt_in_rules:
  - empty_count
reporter: xcode
type_name:
  excluded:
    - ID
vertical_whitespace:
  max_empty_lines: 2
