name: Tests

on:
  push:
    paths-ignore:
      - '.github/**.md'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/**.md'
      - 'README.md'
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  test:
    name: Tests
    runs-on: macos-14    
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Select Swift 5.10
        uses: SwiftyLab/setup-swift@latest
        with:
          check-latest: true
      - name: Report Swift Version
        if: runner.os == 'macOS'
        run: xcrun --toolchain ${{ env.TOOLCHAINS }} swift --version # Swift 5.1.0            
      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: .build
          key: v1-${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            v1-${{ runner.os }}-spm-
      - name: Test
        run: make test-all
