name: Tests

on:
  push:
    paths-ignore:
      - '.github/**.md'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/**.md'
      - 'README.md'
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Swift ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.9", "5.10"]
        include:
          - swift: 5.9
            xcode: 15.1
            os: macos-14
          - swift: 5.10
            xcode: 15.3
            os: macos-14
    steps:
      - name: Setup Xcode version
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Get swift version
        run: swift --version

      - name: Checkout Package
        uses: actions/checkout@v4

      - name: Test
        run: make test-all

      - name: Swift Coverage Report
        continue-on-error: true
        uses: maxep/spm-lcov-action@0.3.1
        with:
          file-format: lcov
          output-file: ./coverage.lcov
